seconds_between_messages: 30
database:
  enabled: false
  ConnectionStrings:
    default: "Server=127.0.0.1; Database=openmod; Port=3306; User=root; Password=toor;"
motd:
  - text: "Welcome to {SERVERNAME}! How are you doing today?"
    color: "#FFFFFF"
  - text: "There are {ONLINEPLAYERS}/{MAXPLAYERS} players."
    color: "#FFFFFF"
  - text: "Have fun!"
    color: "#FFFFFF"
broadcasts:
  - text: "Welcome to {SERVERNAME}!"
    color: "#FFFFFF"
    imageURL: "https://static.wikia.nocookie.net/logopedia/images/4/4e/Unturned_%28Icon%29.jpg"
  - text: "Join our discord! /discord"
    color: "#FFFFFF"
